### ISSUE TITLE
Using both navigation and progress bar causes formatting problems.

### ISSUE THREAD

**Issue by Gauntlet173** [jhpyle/docassemble#49] opened 2018-02-25 01:12 UTC
![image](https://user-images.githubusercontent.com/11790846/36636938-f3fb96fc-198d-11e8-8cae-2832114db257.png)

When the interview is configured with both a progress bar and section titles, the content of the question gets pushed beneath the navigation bar.

Clean install, windows 10, chrome.

**Comment by jhpyle** [comment] 2018-02-25 01:24
What version are you running?  (You can find out under Configuration in the menu.)  This was a problem addressed in 0.1.65.  If you are running the most recent version, I may need some help with reproducing what you are seeing.

**Comment by Gauntlet173** [comment] 2018-02-26 18:56
I'll check and get back to you.  Thanks for your patience.  Busy week.

Regards,



Jason Morris
Round Table Law LLP
jason@roundtablelaw.ca


15C, 2016 Sherwood Drive
Sherwood Park, AB T8A 3X3 (map
<https://local.google.ca/maps?q=Round+Table+Law,+Sherwood+Park,+AB&hl=en&sll=54.498365,-115.000188&sspn=17.901561,53.569336&hq=Round+Table+Law,&hnear=Sherwood+Park,+Division+No.+11,+Alberta&t=m&z=14&iwloc=A>
)
Phone: 1.855.803.1785 Ext: 100 (toll-free)
Fax: 1.855.803.1785 (toll-free)
OpenPGP signature <https://www.roundtablelaw.ca/lawyer/jason-morris>
www.roundtablelaw.ca

**Comment by jhpyle** [comment] 2018-03-04 14:11
Closing because this was from an earlier version.

**Closed by jhpyle** 2018-03-04 14:11 UTC
