### ISSUE TITLE
Bug: screen not scrollable on iOS chrome or safari for final attachment page

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#16] opened 2017-02-04 07:13 UTC
In both chrome and safari, the screen becomes unzoomable and unscrillable even though the document download links are off screen. 

I will attach an image when I'm back to a real computer.

**Comment by jrmiller82** [comment] 2017-02-04 07:15
[https://imgur.com/a/9GWuh](url)

**Comment by jhpyle** [comment] 2017-02-04 15:17
Does it have the same problem on [this example interview](https://demo.docassemble.org/?i=docassemble.base:data/questions/examples/document-variable-name.yml)?

I tried this example on an iPhone using Safari, and an iPad Mini using Chrome and Safari, but I didn't have any problems scrolling or zooming.  It could be that there is something about the HTML version of your document (which is in the Preview tab) that is interfering with the ordinary functioning of the screen.

If you can share with me a link to the interview, or share the code for the page, that might help me figure out what is causing the problem.  You can e-mail me at jhpyle@gmail.com.

**Comment by jrmiller82** [comment] 2017-02-04 16:26
Your example works fine. I will send you example code when I have more computer time. I had the allow downloading: false set as well as restricted to PDF only. I wonder if something goes wrong in that situation.

**Comment by jrmiller82** [comment] 2017-02-04 17:24
```
---
mandatory: True
question: Your document is ready for final review.
subquestion: |
  Please review the final document that will be sent to the Law Office.
  This is your last chance to exit without sending information to the
  Law Office. 
  
  Are you ready to send your responses to the Law Office?
field: readytosend
buttons:
  - Yes: True
  - No: False
    
attachment:
  - name: Conflict Check Document
    description: This is the document that will be emailed to the law office.
    filename: Conflict_Check_Document
    valid formats:
      - pdf
    variable name: ccd
    content: ${ template_ccd }
allow emailing: False
---
mandatory: true
code: |
  if readytosend == True:
    conclusion
  if readytosend == False:
    exitall
---
```

`conclusion` and `exitall` are events that are possible 'final pages' of the interview.

**Comment by jhpyle** [comment] 2017-02-04 18:24
I couldn't tell from your screenshot whether there is a "Markdown" tab present.  The `debug` directive in the configuration controls whether this tab is present.  It is possible that there is something in your template that inserts special characters into the Markdown tab, which might inject HTML tags into the source and mess up the display in the browser.  The Markdown tab uses `<pre> ... </pre>` tags, which are normally safe, but maybe not safe enough.  If there is a Markdown tab, and you open it, does it look messed up in any way?

Are there any problems running this [test interview](https://demo.docassemble.org/?i=docassemble.playground1%3Aattach_error.yml)?

I know that there are issues with Bootstrap where certain popup elements cause scrolling and zooming issues on some mobile devices, but this screen doesn't use any of those features of bootstrap.

By the way, since the mandatory code block will ask for "readytosend," the question that sets "readytosend" does not need to be marked as mandatory.  It is probably a good practice to have as few "mandatory" blocks as possible.

Also, instead of "buttons" you can just use "yesno."

```
---
question: Your document is ready for final review.
subquestion: |
  Please review the final document that will be sent to the Law Office.
  This is your last chance to exit without sending information to the
  Law Office. 
  
  Are you ready to send your responses to the Law Office?
yesno: readytosend
attachment:
  - name: Conflict Check Document
    description: This is the document that will be emailed to the law office.
    filename: Conflict_Check_Document
    valid formats:
      - pdf
    variable name: ccd
    content: ${ template_ccd }
allow emailing: False
---
mandatory: true
code: |
  if readytosend:
    conclusion
  else:
    exitall
---
event: conclusion
question: Conclusion
---
event: exitall
question: Exit All
---
template: template_ccd
content: |
  Baa baa black sheep
```

**Comment by jrmiller82** [comment] 2017-02-04 18:34
Let me try out with your tweaks. Thanks for the tips. Still learning the "flow" of the yml.

**Comment by jrmiller82** [comment] 2017-02-04 18:40
Your latest test interview worked fine in iOS Safari. Going to make tweaks to my interview and see if I can track things down.

**Comment by jrmiller82** [comment] 2017-02-04 18:51
Ok tried it again with your above tweaks and the same issue; no scrolling or zooming. I'm wondering if it has to do with the immediately preceding interview question was a signature capture. (There's a signature in my `template_ccd`). 

And no, I don't have a markdown tab present, (`debug` is off). 

I'll also email you a full .yml file. (I'd prefer that file not becoming public on github.) The file is dirty and not well organized yet so my apologies in advance.

**Comment by jrmiller82** [comment] 2017-02-04 22:07
Ok... did some more fiddling and turning things off and on. It now works as intended, EXCEPT I have to hit refresh in Safari each time I do it. In other words, after signing, the attachment screen is frozen and won't scroll or zoom; but, if I hit my browser's refresh, everything is working perfectly. 

This is leading me to believe that maybe somewhere in the pipeline the http server is serving the request before the whole page has been generated dynamically and then it generates itself much faster upon the refresh possibly due to some internal caching? I'll email the updated .yml file that is working but only after a refresh.

**Comment by jhpyle** [comment] 2017-02-04 22:24
You said earlier, "I'm wondering if it has to do with the immediately preceding interview question was a signature capture," and you were 100% correct.  I was able to reproduce the issue and make a fix.  The latest Docker image should fix the problem.  Thanks so much for your help with this!

**Comment by jrmiller82** [comment] 2017-02-04 23:02
Woohoo! Thanks a bunch!

**Comment by jrmiller82** [comment] 2017-02-04 23:07
I'll download and test it in a few days and close the issue when I've verified it's working.

**Comment by jhpyle** [comment] 2017-08-12 23:35
I believe this issue has been fixed, so I am closing it.

**Closed by jhpyle** 2017-08-12 23:35 UTC
