### ISSUE TITLE
Pandoc error generating final stage of interview (document assembly)

### ISSUE THREAD

**Issue by nroach** [jhpyle/docassemble#23] opened 2017-05-04 09:19 UTC
I'm not sure what's causing this beyond the subject line.   The logs don't seem real informative as to what's going on and which things are trying to be concatenated into what.  I'm on a docker image current as of 4/28/17. Here's the log:

```
Error
TypeError: cannot concatenate 'str' and 'NoneType' objects
Log
Traceback (most recent call last):
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/webapp/server.py", line 3125, in index
    interview.assemble(user_dict, interview_status)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 2370, in assemble
    interview_status.populate(question.ask(user_dict, 'None', 'None'))
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 1876, in ask
    attachment_text = self.processed_attachments(user_dict, the_x=the_x, the_i=the_i)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 1908, in processed_attachments
    result_list.append(self.finalize_attachment(item[0], item[1], user_dict))
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 2025, in finalize_attachment
    result['content'][doc_format] = docassemble.base.filter.markdown_to_html(result['markdown'][doc_format], use_pandoc=True, question=self)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/filter.py", line 946, in markdown_to_html
    a = html_filter(unicode(a), status=status, question=question, embedder=embedder)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/filter.py", line 437, in html_filter
    text = re.sub(r'\[FILE ([^,\]]+)\]', lambda x: image_url_string(x, question=question), text)
  File "/usr/share/docassemble/local/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/filter.py", line 437, in <lambda>
    text = re.sub(r'\[FILE ([^,\]]+)\]', lambda x: image_url_string(x, question=question), text)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/filter.py", line 767, in image_url_string
    return('<img class="daicon" style="' + width_string + '" src="' + server.url_finder(file_reference, question=question) + '"/>')
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by jhpyle** [comment] 2017-05-04 10:11
Yes, an error like that should be trapped better!  It seems like you are making reference to a graphics file which exists but is not displayable for some reason.  If it is a file in a package, it needs to be in the `data/static` folder in order to be displayable.  Or is it a file uploaded by the user?

**Comment by nroach** [comment] 2017-05-04 18:43
Thanks for the speedy reply!  It's a file in my data/static folder.  I've
tried both JPG and PNG versions of the same file and they both appear to be
failing in the same manner.

The weird thing is, they show up in the document preview but result in an
error when pandoc goes to compose the document.

You can see the package that's causing the problem at
https://github.com/nroach/docassemble-GD-IJ-EngagementLetter

**Comment by nroach** [comment] 2017-05-04 18:56
Appearing in Preview 
<img width="294" alt="screenshot 2017-05-04 13 52 51" src="https://cloud.githubusercontent.com/assets/126543/25720093/49d8440e-30d1-11e7-9797-b87e82c19c43.png">

Shows as downloadable
<img width="281" alt="screenshot 2017-05-04 13 53 31" src="https://cloud.githubusercontent.com/assets/126543/25720121/6161d4b4-30d1-11e7-8e0d-2a80b8330fdc.png">

Produces a zero-byte PDF or RTF file when downloaded
<img width="429" alt="screenshot 2017-05-04 13 53 42" src="https://cloud.githubusercontent.com/assets/126543/25720129/68a56efc-30d1-11e7-93ba-d8be8d95c44d.png">

**Comment by jhpyle** [comment] 2017-05-05 01:12
I think the image inclusion problem might be remedied by writing `[FILE firmlogo.jpg]`, though what you did should have worked -- I will need to test that more thoroughly.

As for the Pandoc problem, I think that's caused by the inclusion of the address block within a Markdown table.  Markdown tables are fragile.  However, the `[BEGIN_TWOCOL] ... [BREAK] ... [END_TWOCOL]` construct [documented here](http://docassemble.org/docs/documents.html#markup) might be a good alternative.

**Comment by jhpyle** [comment] 2017-05-05 10:38
I believe the image inclusion problem may have been caused by the fact that your package name had hyphens in it.  I think if you include hyphens in your package name, Python treats the hyphens as minus signs and tries to do subtraction.  I tried taking out the hyphens from the package name and then the image references worked.

**Comment by jhpyle** [comment] 2017-05-05 13:15
Check out [this example](https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/data/questions/examples/twocol.yml) to see how the `[BEGIN_TWOCOL] ... [BREAK] ... [END_TWOCOL]` feature can be used and an address block can be incorporated.
I think the inclusion of the address block using the `.address_block()` method will require the latest version of the software (which is compiling now on Docker Hub) but even with the older version you should be able to construct the address block if you do it one line at a time.

**Comment by jhpyle** [comment] 2017-08-12 23:32
I believe this issue has been addressed, so I am closing it.

**Closed by jhpyle** 2017-08-12 23:32 UTC
