### ISSUE TITLE
Changing github connection causes issues

### ISSUE THREAD

**Issue by prisonblues** [jhpyle/docassemble#130] opened 2019-03-08 11:49 UTC
When I changed the github account for saving packages, I now get errors.  On the user account which was previously authorised, I get `github_configure: error setting public key` when I try to re-set it.

**Comment by jhpyle** [comment] 2019-03-08 12:20
I haven't seen that before.  That error message happened because GitHub rejected your docassemble server's attempt to install your SSH certificate into your GitHub account.  Maybe GitHub has a policy of not allowing two accounts to share the same SSH certificate.  You could try logging into GitHub under the old account and going to your account "Settings" -> "SSH and GPG keys" and then delete the "docassemble" certificate.  Then on your docassemble server, re-do the process of linking to your new GitHub account.

**Comment by jhpyle** [comment] 2019-03-08 12:40
Clicking the "Disable" button on the GitHub integration page in docassemble deletes the SSH keys from GitHub and from the Playground, so if you clicked Disable, you shouldn't see an SSH key in your old account.  There might be something else that is blocking your server from installing a new SSH key in your GitHub account.

**Comment by jhpyle** [comment] 2019-07-12 10:32
I am closing this because I am not sure what changes I could make to avoid errors like this in the future.  I did make some changes to GitHub integration code in March 2019 after this issue was created, but I am not sure those changes would have prevented the error in this case (which I wasn't able to reproduce).  In any case, feel free to reopen this issue if there continues to be a problem.

**Closed by jhpyle** 2019-07-12 10:32 UTC
