### ISSUE TITLE
Partial recovery of backup files

### ISSUE THREAD

**Issue by prisonblues** [jhpyle/docassemble#137] opened 2019-03-27 16:45 UTC
I have a docassemble instance which keeps restarting due to some Azure issues, which I am trying to get to the bottom of.  When it restarts, however, it is part way reset.  

I am using application settings to define azure container settings for blob storage.

After it resets however, the only account I can log in to is admin@admin.com with the default password, the config.yml is reset, none of the user accounts exist.  However, an interview that the admin@admin.com user created is still there, along with templates and files that I uploaded under that account.  When I look in Azure Storage Explorer I can see the folders and files of a few other users.

So it seems that the blob storage works ok, but not some of the databases which hold user info?   The config.yml has been re-created however as part of the re-start (which sits right next to the folders which are still there and working).  Is this a bug?  Or a settings issue?  Seems odd that we can write but not read config.yml, and other database files.

**Comment by jhpyle** [comment] 2019-03-27 17:20
You might want to try doing `docker -t60 stop <containerID>` and a fresh `docker run`.

It seems like your daily cron job is not working for some reason.  If you follow the [Docker troubleshooting instructions](https://docassemble.org/docs/docker.html#troubleshooting) and look at the `/var/mail/mail` file, there might be some error messages from cron.

On a daily basis, the daily cron process is supposed to back up your PostgreSQL database and store it in the `postgres` folder of your Azure Blob Storage container.  Then, if the container crashes and restarts, it will restore the SQL database from that location.  So when it restores, all of your account information should be there (unless it is newer than a day ago).

In addition, the daily cron job is supposed to save daily snapshots to the `backup` folder in Azure Blob Storage.

The config.yml is not supposed to be overwritten, but I think it could be overwritten if the connection to Azure failed at one point and then was later restored.

I will try to see if I can reproduce.  Someone else who was using Azure reported something similar, so there might be an Azure-related issue.

**Comment by prisonblues** [comment] 2019-03-27 18:15
Thanks - I'll investigate on that basis.  It was newer than a day - so there won't be backups (but I have had similar issues in a test instance which did have backups).  The Azure web app seemed to restart very regularly on Azure because of a LowSwapSpace error (have now put it on a more powerful plan) - and maybe that abrupt restart breaks the database.  But the config.yml is/was definitely getting overwritten.

**Comment by rdeshpande** [comment] 2019-03-27 20:23
This exact thing is happening to us.

**Comment by jhpyle** [comment] 2019-03-27 23:09
How did you start the Docker container?  Did you create a Virtual Machine on Azure, then ssh to it, and then run `docker run` from the command line?

**Comment by prisonblues** [comment] 2019-03-27 23:17
No, it just auto-started once set up and the settings set. I think in fact it auto starts, then when you set from its point of view, change) settings, it restarts it all. Could be the problem?

**Comment by jhpyle** [comment] 2019-03-27 23:31
How did you set it up originally if not by ssh'ing to a Virtual Machine and running Docker from the command line?  Did you use some type of front end to Docker like Azure Container Service?

**Comment by prisonblues** [comment] 2019-03-27 23:41
yep - pulled the container to a local registry, then pushed to Azure Container Service (all using command line) then created a web app that references it in the Azure portal.

**Comment by jhpyle** [comment] 2019-03-29 01:01
I tried running docassemble in Azure Container Service to test it out.  It is not clear how `az` commands correspond to `docker` commands.  It seems that `az container start` operates more like `docker run` than `docker start`.  I was able to determine that ACS does not give the Docker container enough time to shut down safely.  Thus it can't save the SQL database to Azure Blob Storage.  

If you use ACS, you should use it with Azure Database for PostgreSQL or Azure Database for MariaDB, as well as Azure Cache for Redis.  That way, nothing will go wrong if the docassemble is abruptly stopped, which Azure seems to do pretty frequently.  Using multiple services in concert is in line with the spirit of "containerization" that ACS encourages.

I was not able to reproduce the problem of the config.yml being overwritten.  Doing an `az container stop` followed by `az container start` preserved the configuration.  However, I could see how the configuration could get overwritten if there was an Azure problem that caused a container to stop and run again.  If Azure Blob Storage is temporarily offline while the docker container is starting up, then docassemble will look for the config.yml file on Azure Blob Storage, and will not find it, and thus it will prepare a fresh configuration file.

**Comment by bennlich** [comment] 2019-04-18 23:28
Hey, @prisonblues . I'm running into the same issue--I wonder if you've found a solution yet?

> If you use ACS, you should use it with Azure Database for PostgreSQL or Azure Database for MariaDB, as well as Azure Cache for Redis.

@jhpyle Just to clarify, this would mean configuring the containerized docassemble to point to external postgres and redis services, yes? I'm looking at https://docassemble.org/docs/config.html#db and https://docassemble.org/docs/config.html#redis.

I'm also considering using a regular VM instead of an Azure Container Service VM. Seems like I might have more control that way.

**Comment by jhpyle** [comment] 2019-04-19 01:09
Yes, @bennlich, the `db` and `redis` Configuration directives are what you would use to connect to external postgres and redis services.

Alternatively if you ran on a regular VM you could have control over shutdown time and then you could run everything on one box.

But in production it is good to externalize by using Azure Blob Service and external SQL and redis.  Then there is much less to worry about.

**Comment by bennlich** [comment] 2019-04-19 02:26
> Yes, @bennlich, the db and redis Configuration directives are what you would use to connect to external postgres and redis services.

Kk, great.

> But in production it is good to externalize by using Azure Blob Service and external SQL and redis. Then there is much less to worry about.

If I'm using external SQL and redis, do I still need Azure Blob Service?

**Comment by bennlich** [comment] 2019-04-19 02:37
> The Azure web app seemed to restart very regularly on Azure because of a LowSwapSpace error

@prisonblues I'm curious how you discovered this particular error. I've been poring over various logs but I haven't been able to figure out why my resource is rebooting.

**Comment by bennlich** [comment] 2019-04-19 05:32
Ah. I was wrong--I am actually not using Azure Container Service. I am running into this problem with Azure Web App for Containers.

**Comment by klt-drafthouse** [comment] 2019-04-19 06:04
@bennlich - I was also using Azure Web App for Containers, and could not get it working, even after trying the redis and external SQL suggestions. Instead used a full Ubuntu VM and it has worked great since. 

I can't remember exactly how I saw the LowSwaoSpace error, and am in mobile right now so can't recreate it. If you click on the 'diagnoatics' type option, there is then a text search box for types of diagnostic. Type 'restart' and it suggests a helpful report.

**Comment by prisonblues** [comment] 2019-04-19 06:06
@bennlich - I was also using Azure Web App for Containers, and could not get it working, even after trying the redis and external SQL suggestions. Instead used a full Ubuntu VM and it has worked great since.

I can't remember exactly how I saw the LowSwaoSpace error, and am in mobile right now so can't recreate it. If you click on the 'diagnostics' type option, there is then a text search box for types of diagnostic. Type 'restart' and it suggests a helpful report.

**Comment by jhpyle** [comment] 2019-04-19 10:09
@bennlich Azure Blob Storage stores files such as files users upload.  SQL stores interview answers, user profiles, and other things.  Redis stores information for fast access.  So you need all three.

I haven't tried using Azure Web App for Containers.  It seems like it is similar to the AWS ECS system described in the Scalability section of the Docassemble documentation.  It is probably possible to implement a multi-server Docassemble configuration on Azure Web App for Containers, but it is likely a 30-step process where each step needs to be performed perfectly or else there is a fatal and difficult-to-debug problem.

**Comment by bennlich** [comment] 2019-04-23 23:23
Hey @jhpyle I started working with an Azure VM instead of Azure Container for WebApp which makes it much easier for me to get inside and look at the logs.

I ran the container with no env vars, then edited the config.yaml in the web interface to point to my azure blob storage. Then I stopped and started the container. I'm seeing this in the supervisor logs:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/list-cloud.py", line 33
    print key.name
            ^
SyntaxError: Missing parentheses in call to 'print'
```
Wondering if this could be a cause of the issue @prisonblues and I were seeing.

**Comment by jhpyle** [comment] 2019-04-23 23:51
That's a Python 2.7 -> 3.5 error.  Sorry about that.  I guess the reason I hadn't caught that bug already is because I haven't tested the specific combination of Python 3.5 and Azure Blob Storage.  Anyway, the bug will be fixed in the next version.

In the meantime you could do `apt-get install vim` or install some other text editor and manually edit `/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/list-cloud.py` and change line 33 to `print(key.name)` and then stop and start the container, and maybe it will work.

**Comment by bennlich** [comment] 2019-04-24 05:59
:+1: thanks. 

And this could explain the issue we're seeing, right? It looks like this module is used when determining whether to fetch the config.yml from azure: https://github.com/jhpyle/docassemble/blob/master/Docker/initialize.sh#L219-L225.

**Comment by jhpyle** [comment] 2019-04-24 10:17
It's possible that it explains the error, if you were both using Python 3.5.

**Comment by bennlich** [comment] 2019-04-24 16:57
Yep. And I just realized that I have a second azure deployment which has never had these issues and it happens to be on python 2.7.

**Comment by bennlich** [comment] 2019-05-10 06:09
@prisonblues I haven't tested my broken deployment with this fix (I switched to an azure VM), but I'm pretty confident the python3 error was the root cause for me. I think this issue can be closed.

**Closed** 2019-06-26 10:41 UTC
