### ISSUE TITLE
2424

### ISSUE THREAD

**Issue by Kll-8989** [jhpyle/docassemble#752] opened 2024-03-01 07:35 UTC
https://github.com/jhpyle/docassemble/blob/97f77dc486a26a22ba804765bfd7058aabd600c9/docassemble_base/docassemble/base/functions.py#L31

**Comment by jhpyle** [comment] 2024-04-29 12:38
Closing this because it isn't clear what the issue is.

**Closed by jhpyle** 2024-04-29 12:38 UTC
